version: '3.8'

services:
  dev-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    restart: unless-stopped
    networks:
      - transcendence
  
  backend:
    build: ./back
    volumes:
      - /usr/bin/xdg-open:/usr/bin/xdg-open
      - ./back:/app
    ports:
      - 8080:8080
      - 5555:5555
    depends_on:
      - dev-db
    restart: unless-stopped
    networks:
      - transcendence

  frontend:
   build: ./front
   ports:
    - 3000:3000
   volumes:
     - ./front:/app
   depends_on:
     - backend
   restart: unless-stopped
   networks:
     - transcendence

networks:
  transcendence:
